### ISSUE TITLE
DNS doesn't seem to be working correctly on a combined branch with DizzyEgg's battle_engine_v2, item_expansion and pokemon_expansion

### ISSUE THREAD

**Issue by LOuroboros** [Xhyzi/pokeemerald#3]
Title.
I pulled the `dns` branch of this repository in [one of my branches](https://github.com/LOuroboros/pokeemerald/tree/mega_expansion) where I only have the 3 biggest projects of [DizzyEgg](https://github.com/dizzyeggg/) *([battle_engine_v2](https://github.com/dizzyeggg/pokeemerald/tree/battle_engine_v2), [item_expansion](https://github.com/DizzyEggg/pokeemerald/tree/item_expansion) and [pokemon_expansion](https://github.com/DizzyEggg/pokeemerald/tree/pokemon_expansion))* and nothing else, I quickly started a new savefile to test out how things looked now ~~even though it's 7 AM by the time I'm writing this~~ and I noticed that the house of the Player on Littleroot Town looks weird.
![VisualBoyAdvanceM878-2020-06-11_06-57-33](https://user-images.githubusercontent.com/4485172/84372272-40074200-abb1-11ea-96cf-993c7bb84704.png)

**EDIT**: I'm not entirely sure if using the `dns` branch with DizzyEgg's branches is out of its scope, so I apologize in advance in case it is, @Xhyzi.

**EDIT2**: I played around with the clock and the picture essentially depicts how the game looks during night time, so yeah, that's the time frame where the issue happens.

**Comment by adhithchand** [comment]
It's an issue with the lighting system. Either disable it by commenting the line 424 "DoDnsLightning();" or you have to modify the array gLightingColours in the file dns.c to fix it.

**Comment by Xhyzi** [comment]
@LOuroboros, It's essentially what @adhithchand said. Is not a problem with the dns itself, but a missconfiguration of the lightning system, which always light up certain colours in the background palettes.

You should edit the aforementioned gLightingColours array to setup which colour slots will be affected by the system.
